.\" Simple Groff Document
.\" This is a comment
.SH NAME .\" Name and title of document
MyGroffDocument \- An Example Groff Document

.SH SYNOPSIS .\" describe the syntax or usage of a command or program.
.B MyGroffDocument
[OPTION]... [FILE]...

.SH DESCRIPTION
This is a simple example of a Groff document. It demonstrates basic formatting and sections.

.PP
This paragraph is a simple text paragraph. You can write text like this directly in the document.

.P
This is another paragraph.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information.

.TP
.B \-v, \-\-version
Display the version of MyGroffDocument.

.SH FILES
The following files are related to this document:
.IP /etc/mygroff.conf
The configuration file for MyGroffDocument.

.SH SEE ALSO
.BR man (1),
.BR groff (1),
.BR groff_man (7).

.SH AUTHOR
John Doe

